### ISSUE TITLE
Stuck in quickstart

### ISSUE THREAD

**Issue by Uuq114** [tarndt/pmigrate#2]
Hello, I want to try some examples with your program, but I don't know GO. Can you show me an example to build and test your program on Linux? XD

**Comment by tarndt** [comment]
1. If you do not have Go installed, you will of course need to [install it](https://golang.org/doc/install).
2. Git clone repo if you have not already
3. Now go to the directories of each of the command line utils and build them
    1. cd [./pmigrate/pfrez](https://github.com/tarndt/pmigrate/tree/master/pfrez), and run `go build`, now you will have a pfrez binary
    2. cd [./pmigrate/pthaw](https://github.com/tarndt/pmigrate/tree/master/pthaw), and run `go build`, now you will have a pthaw binary
    3. If you wish copy them into your PATH like you would any other executable (or reference them directly)
3.  Now you should be able to run examples similar to the [readme](https://github.com/tarndt/pmigrate#readme)
