### ISSUE TITLE
local and remote migrate

### ISSUE THREAD

**Issue by MDreamChaser** [tarndt/pmigrate#3]
Can this project run between two linux system. if one process could be migrated between two linux systems via ip/port

**Comment by tarndt** [comment]
Yes, the pfeeze destination can be remote (network) and the  pthaw source can new remote (network).
See:
- https://github.com/tarndt/pmigrate#usage
- https://github.com/tarndt/pmigrate/blob/master/pfrez/dests.go#L34
- https://github.com/tarndt/pmigrate/blob/master/pthaw/srcs.go#L23
